### ISSUE TITLE
Add support for NET8.0 in Visual Studio 2022 image

### ISSUE THREAD

**Issue by jrgcubano** [appveyor/build-images#140]
Please, could you add support for NET8.0 to the VS2022 image. https://dotnet.microsoft.com/en-us/download/dotnet/8.0.

Thanks

**Comment by jrgcubano** [comment]
@FeodorFitsner  Any idea if this will be possible soon? Thanks

**Comment by jrgcubano** [comment]
Looks like is coming soon: https://github.com/appveyor/build-images/commit/22217db01d14b5104019c8d6a45348181919a977

cc: @OwenMcDonnell

**Comment by jrgcubano** [comment]
Hi @OwenMcDonnell. Any progress? Thanks

**Comment by yang-xiaodong** [comment]
> Hi @OwenMcDonnell. Any progress? Thanks

Already supported!

**Comment by jrgcubano** [comment]
> > Hi @OwenMcDonnell. Any progress? Thanks
> 
> Already supported!

I do not understand what you mean?
