### ISSUE TITLE
Warning with remote host

### ISSUE THREAD

**Issue by jrgcubano** [appveyor/build-images#143]
Getting the next warning since this morning with Visual Studio 2022 image. Any ideas? CC: @OwenMcDonnell.

![image](https://github.com/appveyor/build-images/assets/3245617/4578011f-5010-4319-8649-1b59942d93b3)

We have not changed anything in appveyor.yml or our code.

**Comment by OwenMcDonnell** [comment]
Can you link to the build/repo on which this is happening?

**Comment by jrgcubano** [comment]
@OwenMcDonnell It's a private one in our organization.

**Comment by OwenMcDonnell** [comment]
I've pushed a patch to some vs2022 images. Can you tell me if you're still experiencing this problem?

**Comment by jrgcubano** [comment]
@OwenMcDonnell Fixed. Thanks!
