### ISSUE TITLE
[Feature Request] Use newer mingw-get from OSDN to install MinGW.org toolchain

### ISSUE THREAD

**Issue by TamirEvan** [appveyor/build-images#42]
MinGW.org has [been moving to being hosted on OSDN.net](https://sourceforge.net/p/mingw/mailman/message/36198954/), with newer releases of their packages (and updated catalogue files) being hosted exclusively on the new site, including the newer mingw-get version 0.6.3-pre-20170905-1 (instead of the 0.6.2-beta-20131004-1 on SourceForge).

Whereas mingw-get version 0.6.2-beta-20131004-1 installs (for me):
- GCC 6.3.0-1
- binutils 2.28-1 
- libz 1.2.8-1
- w32api & mingwrt 5.0.2

version 0.6.3-pre-20170905-1 currently installs:
- GCC 9.2.0-1
- binutils 2.32-1
- libz 1.2.11-1
- w32api & mingwrt 5.3

(and will probably install newer versions of these and other packages, as they get updated).

Updating to the newer version of mingw-get **should** be as simple as replacing [scripts/Windows/install_mingw.ps1 lines 11-14](https://github.com/appveyor/build-images/blob/fe939fcd0899f8fdc1f45a00c4104c5f1f6e41bc/scripts/Windows/install_mingw.ps1#L10):
```PowerShell
$zipPath = "$($env:TEMP)\mingw-get-0.6.2-mingw32-beta-20131004-1-bin.tar.xz"
$tarPath = "$($env:TEMP)\mingw-get-0.6.2-mingw32-beta-20131004-1-bin.tar"
Write-Host "Downloading..."
(New-Object Net.WebClient).DownloadFile('http://sourceforge.net/projects/mingw/files/Installer/mingw-get/mingw-get-0.6.2-beta-20131004-1/mingw-get-0.6.2-mingw32-beta-20131004-1-bin.tar.xz/download', $zipPath)
```
with:
```PowerShell
$zipPath = "$($env:TEMP)\mingw-get-0.6.3-mingw32-pre-20170905-1-bin.tar.xz"
$tarPath = "$($env:TEMP)\mingw-get-0.6.3-mingw32-pre-20170905-1-bin.tar"
Write-Host "Downloading..."
(New-Object Net.WebClient).DownloadFile('https://osdn.net/dl/mingw/mingw-get-0.6.3-mingw32-pre-20170905-1-bin.tar.xz', $zipPath)
```
I emphasize that it "_should_" work because, though I have succeeded manually downloading and installing from the link, and have been doing something similar with the AppVeyor build [for one of my GitHub projects](https://github.com/TamirEvan/mupdf/blob/30b3181fc7373247246318033aab54335c027da2/appveyor.yml#L8) with [success](https://ci.appveyor.com/project/TamirEvan/mupdf/build/job/e4rb904pktr3ntsp#L5), I haven't tried running the updated PowerShell script I suggest (especially not in the context of creating an appveyor image).

**Comment by FeodorFitsner** [comment]
Thanks, will get that into the current update: https://github.com/appveyor/ci/issues/3356
Updated script: https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_mingw.ps1

**Comment by Biswa96** [comment]
MinGW from OSDN is ancient, try to use [MinGW-w64][1].

[1]: https://sourceforge.net/projects/mingw-w64/

**Comment by GitMensch** [comment]
While some people see MinGW to be "ancient" it still has its place ...
@FeodorFitsner as you've already made that change years ago (and that mingw-get is still the "current" one) this issue can be closed, can't it?
