### ISSUE TITLE
minimal-ubuntu.json needs updating.

### ISSUE THREAD

**Issue by saltydk** [appveyor/build-images#64]
When attempting to setup my own cloud with the build-cloud wizard and select Ubuntu 18.04 minimal it does not work at all. Firstly the specified ISO is no longer available (2 versions out of date?) but manually updating that still leaves me with an error once it gets to https://github.com/appveyor/build-images/blob/2107b26ac3f48fc28f51eb472a25af8f83a2618f/minimal-ubuntu.json#L40-L44

Where it returns something like:
```
==> hyperv-iso: Downloading versions-20200926223335.log => ./
==> hyperv-iso: Download failed: scp: versions-20200926223335.log: No such file or directory
```

**Comment by saltydk** [comment]
Forgot to mention that the setup is using Hyper-V on Windows Server 2019.

**Comment by FeodorFitsner** [comment]
It's been [fixed](https://github.com/appveyor/build-images/commit/27bde614bc60d7ef7a8bc46182f4d7582fa11b56), please give it another try.

**Comment by saltydk** [comment]
Thanks, that was ultimately what I edited my own file to in the end but I have no knowledge of packer prior to this so happy to know I didn't break it :D
