### ISSUE TITLE
VS 2019 - add Address Sanitizer

### ISSUE THREAD

**Issue by adbancroft** [appveyor/build-images#85]
The VS 2019 compiler supports Address Sanitizer, which requires an extra library. At the moment, compiling with `-fsanitize=address` results in a linker error:

- `LINK : fatal error LNK1104: cannot open file 'clang_rt.asan_dbg-x86_64.lib'`

Please add the Address Sanitizer component to the VS 2019 install. The [MS docs list](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019) it as:

- `Microsoft.VisualStudio.Component.VC.ASAN`

**Comment by FeodorFitsner** [comment]
It's been added in the recent image update: https://www.appveyor.com/updates/2021/06/14/
