### ISSUE TITLE
Provide binaries for Boost 1.77

### ISSUE THREAD

**Issue by reneme** [appveyor/build-images#94]
It seems that the "Visual Studio 2019" image provides compiled binaries for [Boost 1.73](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_boost_1.73.0_vs2019.ps1) but merely the source package for [Boost 1.77](https://github.com/appveyor/build-images/blob/master/scripts/Windows/install_boost_1.77.0_vs2019.ps1). Or am I missing something?

It would be great to have binaries for Boost 1.77 as well.

**Comment by FeodorFitsner** [comment]
Yep, will fix it during the next image update. Thanks for letting know.

**Comment by GitMensch** [comment]
@FeodorFitsner Any idea when the next image update will be? Do you think you could tackle vcpkg and dependencies (see #96) with that, too?

**Comment by FeodorFitsner** [comment]
The latest image update already contains 1.77 binaries: https://www.appveyor.com/updates/2021/11/02/

**Comment by GitMensch** [comment]
Hm, that only is related to the VS2019 build, but then this is what was requested.
I suggest to close this issue (and possibly go on to the other one for the next update).
